version: '3.8'
services:
  database:
    container_name: user_database
    image: percona/percona-server:latest
    ports:
      - "3311:3306"
    environment:
      - MYSQL_DATABASE=user-platform
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=terrible
    volumes:
      - mysql-user-database:/var/lib/mysql
volumes:
  mysql-user-database:
