version : '3.8'
services :
  database:
    container_name: user_database
    image: percona/percona-server:latest
    ports:
      - 3311:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql-user-database:/var/lib/mysql